# Database ORM mapper
development: &defaults
  adapter:  sqlite3
  database: db/development.db
    
production: &defaults
  adapter:  mysql
  database: whosreadingwhat_production
  username: whosreadingwhat
  password: 5tup1dp455w0rd
  host:     localhost
  socket:   /var/run/mysqld/mysqld.sock

